local game=game
local task=task
local type=type
local tonumber=tonumber
local pairs=pairs
local ipairs=ipairs
local math_max=math.max
local os_clock=os.clock
local Factory={}
local comboIDs={[10480793962]=true,[10480796021]=true}
local allIDs={Saitama={10469493270,10469630950,10469639222,10469643643,special=10479335397},Garou={13532562418,13532600125,13532604085,13294471966,special=10479335397},Cyborg={13491635433,13296577783,13295919399,13295936866,special=10479335397},Sonic={13370310513,13390230973,13378751717,13378708199,special=13380255751},Metal={14004222985,13997092940,14001963401,14136436157,special=13380255751},Blade={15259161390,15240216931,15240176873,15162694192,special=13380255751},Tatsumaki={16515503507,16515520431,16515448089,16552234590,special=10479335397},Dragon={17889458563,17889461810,17889471098,17889290569,special=10479335397},Tech={123005629431309,100059874351664,104895379416342,134775406437626,special=10479335397}}
local skillIDs={[10468665991]=true,[10466974800]=true,[10471336737]=true,[12510170988]=true,[12272894215]=true,[12296882427]=true,[12307656616]=true,[101588604872680]=true,[105442749844047]=true,[109617620932970]=true,[131820095363270]=true,[135289891173395]=true,[125955606488863]=true,[12534735382]=true,[12502664044]=true,[12509505723]=true,[12618271998]=true,[12684390285]=true,[13376869471]=true,[13294790250]=true,[13376962659]=true,[13501296372]=true,[13556985475]=true,[145162735010]=true,[14046756619]=true,[14299135500]=true,[14351441234]=true,[15290930205]=true,[15145462680]=true,[15295895753]=true,[15295336270]=true,[16139108718]=true,[16515850153]=true,[16431491215]=true,[16597322398]=true,[16597912086]=true,[17799224866]=true,[17838006839]=true,[17857788598]=true,[18179181663]=true,[113166426814229]=true,[116753755471636]=true,[116153572280464]=true,[114095570398448]=true,[77509627104305]=true}
local function disconnectAll(list) if not list then return end for i=#list,1,-1 do local c=list[i] list[i]=nil if c then pcall(c.Disconnect,c) end end end
local function getAnimationId(track) if not track then return nil end local ok,a=pcall(function() return track.Animation end) if not ok or not a then return nil end local okId,id=pcall(function() return a.AnimationId end) if not okId or type(id)~="string" then return nil end return tonumber(id:match("%d+")) end
function Factory.new(context)
 context=context or {}
 local Players=context.Players or game:GetService("Players")
 local RunService=context.RunService or game:GetService("RunService")
 local VirtualInputManager=context.VirtualInputManager or game:GetService("VirtualInputManager")
 local Workspace=context.Workspace or game:GetService("Workspace")
 local LocalPlayer=context.LocalPlayer or Players.LocalPlayer
 local self={Enabled=false,Destroyed=false,Connections={},Playing=setmetatable({},{__mode="k"}),M1ingState=setmetatable({},{__mode="k"}),InsideState=setmetatable({},{__mode="k"}),CatchPending=setmetatable({},{__mode="k"}),LastCatch=0,BlockActive=false,BlockUntil=0,DetectionPart=nil,DetectionCharacter=nil,CharacterToken=0,DebugInfo={Runtime="idle",Character="none",Remote="missing",Live="missing",LastEvent="none",LastAnimation="none",LastPlayer="none",LastDistance=0,Blocks=0,LastError="none"},Config={M1Block=context.M1Block==true,DashBlock=context.DashBlock==true,SkillBlock=context.SkillBlock==true,NormalRange=tonumber(context.NormalRange) or 12,SpecialRange=tonumber(context.SpecialRange) or 50,SkillRange=tonumber(context.SkillRange) or 50,SkillHold=tonumber(context.SkillHold) or 1.2,M1AfterBlock=context.M1AfterBlock==true,M1Catch=context.M1Catch==true,DetectionBoxSize=tonumber(context.DetectionBoxSize) or 12,ShowDetectionBox=context.ShowDetectionBox==true,Debug=context.Debug==true}}
 function self:_debug(text) self.DebugInfo.LastEvent=tostring(text) if self.Config.Debug then print("[DepHub TSB] "..tostring(text)) end end
 function self:_resetCombatState(reason) self.BlockActive=false self.BlockUntil=0 self.Playing=setmetatable({},{__mode="k"}) self.M1ingState=setmetatable({},{__mode="k"}) self.InsideState=setmetatable({},{__mode="k"}) self.CatchPending=setmetatable({},{__mode="k"}) if reason then self:_debug(reason) end end
 function self:_destroyDetectionBox() if self.DetectionPart then pcall(self.DetectionPart.Destroy,self.DetectionPart) end self.DetectionPart=nil self.DetectionCharacter=nil end
 function self:_communicate(goal,mobile) if self.Destroyed or not LocalPlayer then return false end local character=LocalPlayer.Character local remote=character and character:FindFirstChild("Communicate") self.DebugInfo.Character=character and character.Name or "none" self.DebugInfo.Remote=remote and remote:IsA("RemoteEvent") and "ready" or "missing" if not remote or not remote:IsA("RemoteEvent") then return false end local payload={Goal=goal,Mobile=mobile or nil} if goal=="KeyPress" or goal=="KeyRelease" then payload.Key=Enum.KeyCode.F end local ok,err=pcall(remote.FireServer,remote,payload) if not ok then self.DebugInfo.LastError=tostring(err) self:_debug("remote error: "..tostring(err)) end return ok end
 function self:_ensureDetectionBox() local character=LocalPlayer and LocalPlayer.Character local root=character and character:FindFirstChild("HumanoidRootPart") if not character or not root then return nil end if self.DetectionPart and self.DetectionPart.Parent and self.DetectionCharacter==character then local s=self.Config.DetectionBoxSize self.DetectionPart.Size=Vector3.new(s,s,s) self.DetectionPart.Transparency=self.Config.ShowDetectionBox and .68 or 1 return self.DetectionPart end self:_destroyDetectionBox() local s=self.Config.DetectionBoxSize local part=Instance.new("Part") part.Name="DepHubDetectionBox" part.Size=Vector3.new(s,s,s) part.CFrame=root.CFrame part.Color=Color3.fromRGB(255,55,55) part.Material=Enum.Material.Plastic part.Transparency=self.Config.ShowDetectionBox and .68 or 1 part.CanCollide=false part.CanTouch=false part.CanQuery=false part.CastShadow=false part.Massless=true part.Anchored=false part.Parent=character local weld=Instance.new("WeldConstraint") weld.Part0=root weld.Part1=part weld.Parent=part self.DetectionPart=part self.DetectionCharacter=character self:_debug("hitbox criada: "..tostring(s).."x"..tostring(s).."x"..tostring(s)) return part end
 function self:_insideDetectionBox(enemyRoot,myRoot) if not enemyRoot or not myRoot then return false end local p=myRoot.CFrame:PointToObjectSpace(enemyRoot.Position) local half=self.Config.DetectionBoxSize*.5 return math.abs(p.X)<=half and math.abs(p.Y)<=half and math.abs(p.Z)<=half end
 function self:_pressBlock(duration,reason,player,id,distance) if self.Destroyed or not self.Enabled then return end local now=os_clock() self.BlockUntil=math_max(self.BlockUntil,now+(tonumber(duration) or .15)) if reason then self.DebugInfo.LastAnimation=id and tostring(id) or "none" self.DebugInfo.LastPlayer=player and player.Name or "none" self.DebugInfo.LastDistance=tonumber(distance) or 0 self:_debug("block "..reason.." | "..self.DebugInfo.LastPlayer.." | id="..self.DebugInfo.LastAnimation.." | dist="..string.format("%.1f",self.DebugInfo.LastDistance)) end if self.BlockActive then return end if self:_communicate("KeyPress") then self.BlockActive=true self.DebugInfo.Blocks=self.DebugInfo.Blocks+1 end end
 function self:_releaseBlock() if not self.BlockActive then return end self:_communicate("KeyRelease") self.BlockActive=false self.BlockUntil=0 end
 function self:_leftClick() if self.Destroyed or not self.Enabled then return end self:_communicate("LeftClick",true) task.delay(.3,function() if not self.Destroyed and self.Enabled then self:_communicate("LeftClickRelease",true) end end) end
 function self:_afterBlock(enemyRoot) if not self.Config.M1AfterBlock or not enemyRoot or self.Destroyed or not self.Enabled then return end local character=LocalPlayer.Character local root=character and character:FindFirstChild("HumanoidRootPart") if root and enemyRoot.Parent and (enemyRoot.Position-root.Position).Magnitude<=10 then self:_debug("M1 After Block") self:_leftClick() end end
 function self:_startCatch(player,enemyRoot) if not self.Config.M1Catch or self.Destroyed or not self.Enabled or self.CatchPending[player] or os_clock()-self.LastCatch<5 then return end local character=LocalPlayer.Character local myRoot=character and character:FindFirstChild("HumanoidRootPart") if not myRoot or not enemyRoot then return end local dist1=(enemyRoot.Position-myRoot.Position).Magnitude if dist1>self.Config.SpecialRange then return end self.CatchPending[player]=true task.delay(.1,function() self.CatchPending[player]=nil if self.Destroyed or not self.Enabled or not self.Config.M1Catch then return end local current=LocalPlayer.Character local root=current and current:FindFirstChild("HumanoidRootPart") if not root or not enemyRoot.Parent then return end local dist2=(enemyRoot.Position-root.Position).Magnitude if dist2>=dist1-.5 or os_clock()-self.LastCatch<5 then return end self.LastCatch=os_clock() self:_debug("M1 Catch: "..player.Name) self:_communicate("LeftClick",true) task.delay(.2,function() if not self.Destroyed and self.Enabled then self:_communicate("LeftClickRelease",true) end end) pcall(VirtualInputManager.SendKeyEvent,VirtualInputManager,true,Enum.KeyCode.D,false,game) pcall(VirtualInputManager.SendKeyEvent,VirtualInputManager,true,Enum.KeyCode.Q,false,game) task.delay(1,function() pcall(VirtualInputManager.SendKeyEvent,VirtualInputManager,false,Enum.KeyCode.Q,false,game) pcall(VirtualInputManager.SendKeyEvent,VirtualInputManager,false,Enum.KeyCode.D,false,game) end) end) end
 function self:_scanPlayer(player,live,myRoot)
  if player==LocalPlayer then return end
  local character=player.Character if not character or character.Parent~=live then self.Playing[player]=nil self.M1ingState[player]=nil self.InsideState[player]=nil return end
  local enemyRoot=character:FindFirstChild("HumanoidRootPart") local humanoid=character:FindFirstChildWhichIsA("Humanoid") if not enemyRoot or not humanoid or humanoid.Health<=0 then return end
  local distance=(enemyRoot.Position-myRoot.Position).Magnitude local inside=self:_insideDetectionBox(enemyRoot,myRoot) local wasInside=self.InsideState[player]==true self.InsideState[player]=inside
  local m1ing=character:FindFirstChild("M1ing")~=nil local wasM1ing=self.M1ingState[player]==true self.M1ingState[player]=m1ing
  if self.Config.M1Block and inside and m1ing and (not wasM1ing or not wasInside) then self:_pressBlock(.15,"M1ing",player,nil,distance) if self.Config.M1AfterBlock then task.delay(.15,function() self:_afterBlock(enemyRoot) end) end return end
  local animator=humanoid:FindFirstChildOfClass("Animator") if not animator then return end
  local current,started={},{} local okTracks,tracks=pcall(animator.GetPlayingAnimationTracks,animator) if not okTracks or type(tracks)~="table" then return end local previous=self.Playing[player] if type(previous)~="table" then previous={} end
  for _,track in ipairs(tracks) do local id=getAnimationId(track) if id then current[id]=true if not previous[id] then started[id]=true end end end self.Playing[player]=current
  local hasStarted=false for _ in pairs(started) do hasStarted=true break end
  local comboCount=0 for id in pairs(comboIDs) do if current[id] then comboCount=comboCount+1 end end
  for _,group in pairs(allIDs) do
   local normalHits,normalStarted,normalCurrent,normalId=0,false,false,nil
   for i=1,4 do local id=group[i] if current[id] then normalHits=normalHits+1 normalCurrent=true normalId=normalId or id end if started[id] then normalStarted=true normalId=id end end
   if self.Config.DashBlock and comboCount==2 and normalHits>=2 and distance<=self.Config.SpecialRange then self:_pressBlock(.7,"combo/dash",player,normalId,distance) return end
   if self.Config.M1Block and inside and distance<=self.Config.NormalRange and (normalStarted or (not wasInside and normalCurrent)) then self:_pressBlock(.15,"M1 animation",player,normalId,distance) if self.Config.M1AfterBlock then task.delay(.15,function() self:_afterBlock(enemyRoot) end) end return end
   if hasStarted and started[group.special] and distance<=self.Config.SpecialRange then if self.Config.M1Block and self.Config.M1Catch and group.special==10479335397 then self:_startCatch(player,enemyRoot) elseif self.Config.DashBlock then self:_pressBlock(1,"special/dash",player,group.special,distance) end return end
  end
  if self.Config.SkillBlock and hasStarted then for id in pairs(started) do if skillIDs[id] and distance<=self.Config.SkillRange then self:_pressBlock(self.Config.SkillHold,"skill",player,id,distance) return end end end
 end
 function self:_onCharacterRemoving(character) if character~=self.DetectionCharacter and character~=LocalPlayer.Character then return end self.CharacterToken=self.CharacterToken+1 self:_destroyDetectionBox() self:_resetCombatState("character removido; aguardando respawn") self.DebugInfo.Character="respawning" self.DebugInfo.Remote="missing" end
 function self:_onCharacterAdded(character) self.CharacterToken=self.CharacterToken+1 local token=self.CharacterToken self:_destroyDetectionBox() self:_resetCombatState("respawn detectado") self.DebugInfo.Character=character.Name self.DebugInfo.Remote="waiting" task.spawn(function() local root=character:WaitForChild("HumanoidRootPart",8) if self.Destroyed or not self.Enabled or token~=self.CharacterToken or LocalPlayer.Character~=character then return end if not root then self.DebugInfo.LastError="HumanoidRootPart timeout" self:_debug("respawn sem HumanoidRootPart") return end character:WaitForChild("Communicate",8) if self.Destroyed or not self.Enabled or token~=self.CharacterToken then return end self.DebugInfo.Remote=character:FindFirstChild("Communicate") and "ready" or "missing" if self.Config.M1Block then self:_ensureDetectionBox() end self:_debug("respawn pronto") end) end
 function self:_step() if self.Destroyed or not self.Enabled then return end local live=Workspace:FindFirstChild("Live") self.DebugInfo.Live=live and "ready" or "missing" local character=LocalPlayer.Character local myRoot=character and character:FindFirstChild("HumanoidRootPart") self.DebugInfo.Character=character and character.Name or "none" local remote=character and character:FindFirstChild("Communicate") self.DebugInfo.Remote=remote and remote:IsA("RemoteEvent") and "ready" or "missing" if self.Config.M1Block and myRoot then self:_ensureDetectionBox() elseif not self.Config.M1Block then self:_destroyDetectionBox() end if self.BlockActive and os_clock()>=self.BlockUntil then self:_releaseBlock() end if not live or not myRoot then return end for _,player in ipairs(Players:GetPlayers()) do self:_scanPlayer(player,live,myRoot) end end
 function self:SetM1Block(v) self.Config.M1Block=v==true if not self.Config.M1Block then self:_destroyDetectionBox() elseif self.Enabled then self:_ensureDetectionBox() end return true end
 function self:SetDashBlock(v) self.Config.DashBlock=v==true return true end
 function self:SetSkillBlock(v) self.Config.SkillBlock=v==true return true end
 function self:SetDebug(v) self.Config.Debug=v==true self:_debug(self.Config.Debug and "debug ligado" or "debug desligado") return true end
 function self:SetNormalRange(v) v=tonumber(v) if not v then return false end self.Config.NormalRange=math.max(0,v) return true end
 function self:SetSpecialRange(v) v=tonumber(v) if not v then return false end self.Config.SpecialRange=math.max(0,v) return true end
 function self:SetSkillRange(v) v=tonumber(v) if not v then return false end self.Config.SkillRange=math.max(0,v) return true end
 function self:SetSkillHold(v) v=tonumber(v) if not v or v<=0 then return false end self.Config.SkillHold=v return true end
 function self:SetM1AfterBlock(v) self.Config.M1AfterBlock=v==true return true end
 function self:SetM1Catch(v) self.Config.M1Catch=v==true return true end
 function self:SetDetectionBoxSize(v) v=tonumber(v) if not v then return false end self.Config.DetectionBoxSize=math.max(2,math.min(40,v)) if self.Config.M1Block and self.Enabled then self:_ensureDetectionBox() end return true end
 function self:SetShowDetectionBox(v) self.Config.ShowDetectionBox=v==true if self.Config.M1Block and self.Enabled then self:_ensureDetectionBox() end return true end
 function self:GetDebugInfo() local out={} for k,v in pairs(self.DebugInfo) do out[k]=v end out.Enabled=self.Enabled out.BlockActive=self.BlockActive out.M1Block=self.Config.M1Block out.DashBlock=self.Config.DashBlock out.SkillBlock=self.Config.SkillBlock return out end
 function self:GetConfig() return {M1Block=self.Config.M1Block,DashBlock=self.Config.DashBlock,SkillBlock=self.Config.SkillBlock,Debug=self.Config.Debug,NormalRange=self.Config.NormalRange,SpecialRange=self.Config.SpecialRange,SkillRange=self.Config.SkillRange,SkillHold=self.Config.SkillHold,M1AfterBlock=self.Config.M1AfterBlock,M1Catch=self.Config.M1Catch,DetectionBoxSize=self.Config.DetectionBoxSize,ShowDetectionBox=self.Config.ShowDetectionBox} end
 function self:Enable() if self.Destroyed then return false end if self.Enabled then return true end self.Enabled=true self.DebugInfo.Runtime="running" self:_resetCombatState("runtime iniciado") self.Connections[#self.Connections+1]=LocalPlayer.CharacterAdded:Connect(function(character) self:_onCharacterAdded(character) end) self.Connections[#self.Connections+1]=LocalPlayer.CharacterRemoving:Connect(function(character) self:_onCharacterRemoving(character) end) self.Connections[#self.Connections+1]=RunService.Heartbeat:Connect(function() local ok,err=pcall(self._step,self) if not ok then self.DebugInfo.LastError=tostring(err) self:_debug("heartbeat error: "..tostring(err)) end end) if LocalPlayer.Character then self:_onCharacterAdded(LocalPlayer.Character) end return true end
 function self:Disable() if self.Destroyed then return false end if not self.Enabled then return true end self.Enabled=false self.DebugInfo.Runtime="idle" self.CharacterToken=self.CharacterToken+1 disconnectAll(self.Connections) self:_releaseBlock() self:_destroyDetectionBox() self:_resetCombatState("runtime parado") return true end
 function self:Destroy() if self.Destroyed then return end self:Disable() self.Destroyed=true self.DebugInfo.Runtime="destroyed" self.Playing=nil self.M1ingState=nil self.InsideState=nil self.CatchPending=nil end
 return self
end
return Factory
